### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by larsonsamj** [wingrunr21/hassio-xcel-itron-mqtt#10]
Just got my smart meter 2 weeks ago and I'm having issues with the add-on staying up. It is pulling data occasionally, but the add-on keeps crashing. I have watchdog enabled so every few hours I'll get updated data. Consistently seeing this in the logs:

```
Traceback (most recent call last):
  File "/opt/xcel_itron2mqtt/main.py", line 88, in <module>
    meter.run()
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 243, in run
    obj.run()
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 180, in run
    reading = self.get_reading()
              ^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 88, in get_reading
    self.current_response = self.parse_response(response, self.tags)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 75, in parse_response
    value = root.find(f'.//{IEEE_PREFIX}{k}').text
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
[12:44:02] INFO: Service Xcel iTron2MQTe exited with code 1 (by signal 0)

```

Everything is default (except IP and LDFI of course). Everything should be configured correctly since it is able to occasionally connect and pull data (although everything is unknown with the exception of "Instantaneous Demand value")

Here is the full excerpt:

```
-----------------------------------------------------------
 Add-on: Xcel iTron MQTT
 Bridge from Xcel iTron smart meters to MQTT
-----------------------------------------------------------
 Add-on version: 1.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.2  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2024.4.3
 Home Assistant Supervisor: 2024.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-xcel-itron-mqtt: starting
[12:43:46] INFO: Initializing Xcel iTron2MQTT
s6-rc: info: service init-xcel-itron-mqtt successfully started
s6-rc: info: service xcel-itron-mqtt: starting
s6-rc: info: service xcel-itron-mqtt successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[12:43:46] INFO: Starting Xcel iTron2MQTT
INFO: Connected to MQTT Broker!
Traceback (most recent call last):
  File "/opt/xcel_itron2mqtt/main.py", line 88, in <module>
    meter.run()
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 243, in run
    obj.run()
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 180, in run
    reading = self.get_reading()
              ^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 88, in get_reading
    self.current_response = self.parse_response(response, self.tags)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelEndpoint.py", line 75, in parse_response
    value = root.find(f'.//{IEEE_PREFIX}{k}').text
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
[12:44:02] INFO: Service Xcel iTron2MQTe exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service xcel-itron-mqtt: stopping
s6-rc: info: service xcel-itron-mqtt successfully stopped
s6-rc: info: service init-xcel-itron-mqtt: stopping
s6-rc: info: service init-xcel-itron-mqtt successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by wingrunr21** [comment]
Are you in MN or WI? looks the same as this:

zaknye/xcel_itron2mqtt#25

**Comment by larsonsamj** [comment]
> Are you in MN or WI? looks the same as this:
> 
> [zaknye/xcel_itron2mqtt#25](https://github.com/zaknye/xcel_itron2mqtt/pull/25)

It sure does look like that. Not sure how I didn't see that lol. I am in MN. So it sounds like I just wait for that fix to get merged into this project.

**Comment by wingrunr21** [comment]
Try `v1.2.0` and see if that works

**Comment by larsonsamj** [comment]
That did the trick, getting a lot more values now and it's no longer crashing. Thanks!
