### ISSUE TITLE
1.3.0: SSL Error

### ISSUE THREAD

**Issue by itwasdolly** [wingrunr21/hassio-xcel-itron-mqtt#21]
Upgraded to 1.3.0, and I'm now seeing this error in my logs:

WARNING: Retrying xcelMeter.xcelMeter.setup in 1.0 seconds as it raised ConnectionError: HTTPSConnectionPool(host='192.168.2.50, port=8081): Max retries exceeded with url: /sdev/sdi (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6218e5d400>: Failed to establish a new connection: [Errno 113] Host is unreachable')).

**Comment by itwasdolly** [comment]
-----------------------------------------------------------
 Add-on: Xcel iTron MQTT
 Bridge from Xcel iTron smart meters to MQTT
-----------------------------------------------------------
 Add-on version: 1.3.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / qemux86-64)
 Home Assistant Core: 2024.10.4
 Home Assistant Supervisor: 2024.10.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------

**Comment by wingrunr21** [comment]
Yes, OpenSSL is pretty unhappy. I'm trying to troubleshoot it

**Comment by itwasdolly** [comment]
Uneducated guess, is it a typo? Should the URL be `/dev/sdi`?

**Comment by wingrunr21** [comment]
No, the meter uses a pretty old cipher and OpenSSL really doesn't like being told to use it. I bumped the base hass addon container and I'm assuming OpenSSL got upgraded and needs something else in the config

**Comment by wingrunr21** [comment]
`1.4.0` looks like it fixes it. I'm going to have to figure out how to accurately test this as it seems the meter behaves slightly differently than the local tests I am doing

**Comment by itwasdolly** [comment]
Thanks, and for the amazingly quick fix!

**Comment by yonghan** [comment]
it seems like the issue persist in 1.4.1:

 Add-on version: 1.4.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 14.1  (amd64 / qemux86-64)
 Home Assistant Core: 2024.12.5
 Home Assistant Supervisor: 2024.12.3

```
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-xcel-itron-mqtt: starting
[10:22:08] INFO: Initializing Xcel iTron2MQTT
s6-rc: info: service init-xcel-itron-mqtt successfully started
s6-rc: info: service xcel-itron-mqtt: starting
s6-rc: info: service xcel-itron-mqtt successfully started
s6-rc: info: service legacy-services: starting
[10:22:08] INFO: Starting Xcel iTron2MQTT
s6-rc: info: service legacy-services successfully started
[10:22:08] INFO: Meter config: 10.10.10.115:8081
[10:22:08] INFO: MQTT server config: core-mosquitto:1883
INFO: Connected to MQTT Broker!
WARNING: Retrying xcelMeter.xcelMeter.setup in 1.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7c7966f0>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 2.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8a4380>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 4.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8a4410>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 8.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7bbdfef0>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 15.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8a4080>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 15.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8a4140>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 15.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8a4a70>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 15.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8a6510>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 15.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8a6870>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 15.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8a6c90>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 15.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8a6fc0>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 15.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8a7440>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 15.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8aaa20>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
WARNING: Retrying xcelMeter.xcelMeter.setup in 15.0 seconds as it raised ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8aa420>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f0f7b8aa840>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8aa840>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/xcel_itron2mqtt/main.py", line 84, in <module>
    meter.setup()
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 76, in setup
    details_dict = self.get_hardware_details(hw_info_url, hw_info_names)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 113, in get_hardware_details
    x = self.requests_session.get(query_url, verify=False, timeout=4.0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='10.10.10.115', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0f7b8aa840>, 'Connection to 10.10.10.115 timed out. (connect timeout=4.0)'))
[10:25:54] INFO: Service Xcel iTron2MQTe exited with code 1 (by signal 0)
```
