### ISSUE TITLE
MQTT configuration info available in the Configuration UI or corresponding YAML ?

### ISSUE THREAD

**Issue by d2inco** [wingrunr21/hassio-xcel-itron-mqtt#22]
Hello.

Any chance you could either make the MQTT Broker part of the Configuration UI, or alternatively, give an example of the 4 entries needed to get it up and running? I was able to locate a '**mqtt_server_address**' and **'mqtt_port'** in the error message and tried those, but still need to be able to get the **MQTT User/Pass** in there, as well

I'm running an external broker, and the reference to it in the documentation, "You can use an external broker other than the Mosquitto addon by configuring the MQTT integration with that broker's details" don't have the 4 specific yaml Keys that need to be set for an external broker.   (If I understood Python better, I'd go diving into it, but... I don't).

Thank you!

**Comment by wingrunr21** [comment]
I'd like to keep to using service discovery vs storing credentials in plain text. I could add an option to the UI to fall back to the manual config options but you need the MQTT integration configured anyway for the entities to show up.

You configure the [MQTT integration](https://www.home-assistant.io/integrations/mqtt/) to use your broker:

![Screenshot 2024-11-06 at 8 15 45 AM](https://github.com/user-attachments/assets/ce31248f-d50a-4b1a-95c4-9dc062fca197)

That's mine for the mosquitto addon.

**Comment by d2inco** [comment]
Ah yes, I do have the MQTT configured with my broker, port, the HASS username and pw in there.   So, maybe it's just not fully getting passed to the Addon ?

**Comment by d2inco** [comment]
This is the MQTT Configuration for my external (within the home network):
![image](https://github.com/user-attachments/assets/0f706e30-537a-4b38-8db9-79dae09dcf91)

This is the Config file of Xcdl-Itron-MQTT (rather than a GUI shot):
```meter_ip: 192.168.REDA.CTED
meter_port: 8081
cert_dir: /config/certs
cert_file: cert.pem
key_file: key.pem
ldfi: REDACTED
```
Yes, the `meter_ip ` is confirmed and does show port 8081 open and responding.


This is the log capture after attempting to start the Xcel iTron MQTT is here:
```----------------------------------------------------------
 Add-on: Xcel iTron MQTT
 Bridge from Xcel iTron smart meters to MQTT
-----------------------------------------------------------
 Add-on version: 1.4.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 12 (bookworm)  (amd64 / qemux86-64)
 Home Assistant Core: 2024.10.4
 Home Assistant Supervisor: 2024.10.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-xcel-itron-mqtt: starting
[09:26:38] INFO: Initializing Xcel iTron2MQTT
s6-rc: info: service init-xcel-itron-mqtt successfully started
s6-rc: info: service xcel-itron-mqtt: starting
s6-rc: info: service xcel-itron-mqtt successfully started
s6-rc: info: service legacy-services: starting
[09:26:39] INFO: Starting Xcel iTron2MQTT
[09:26:39] ERROR: Got unexpected response from the API: Service not enabled
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/opt/xcel_itron2mqtt/main.py", line 83, in <module>
    meter = xcelMeter(INTEGRATION_NAME, ip_address, port_num, creds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 58, in __init__
    self.mqtt_client = self.setup_mqtt(self.mqtt_server_address, self.mqtt_port)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 197, in setup_mqtt
    client.connect(mqtt_server_address, mqtt_port)
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 912, in connect
    self.connect_async(host, port, keepalive,
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 978, in connect_async
    raise ValueError('Invalid host.')
ValueError: Invalid host.
[09:26:40] INFO: Service Xcel iTron2MQTe exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service xcel-itron-mqtt: stopping
s6-rc: info: service xcel-itron-mqtt successfully stopped
s6-rc: info: service init-xcel-itron-mqtt: stopping
s6-rc: info: service init-xcel-itron-mqtt successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
...
```

So I'd think that there should be a `client.username_pw_set(username,password)` in stack trace, too, somewhere that maybe isn't being set?   But again, I'm not a Python guy, so...

**Comment by wingrunr21** [comment]
The Mosquitto addon also uses a username and password, so using an external broker should not be different. But, for sake of completeness: [here's where the username/password is set in the upstream project](https://github.com/zaknye/xcel_itron2mqtt/blob/main/xcel_itron2mqtt/xcelMeter.py#L189-L195) and [here is where this addon extracts the credentials](https://github.com/wingrunr21/hassio-xcel-itron-mqtt/blob/main/xcel-itron-mqtt/rootfs/etc/s6-overlay/s6-rc.d/xcel-itron-mqtt/run#L11-L12)

The error is saying "Invalid host". It's not clear to me if that's because of that "Service not enabled" API error or if your config is incorrect. Are you using the MQTT integration for other things successfully? Have you restarted your Home Assistant instance (a quick Google showed several issues on the `wmbusmeters` project with the same error saying a restart fixed it for some reason).

**Comment by d2inco** [comment]
Yeah, I use the MQTT successfully (407 devices, 501 entities).

I see the two code-links you provided, and it makes some sense with:
```export MQTT_SERVER=$(bashio::services mqtt "host")
export MQTT_USER=$(bashio::services mqtt "username")
export MQTT_PASSWORD=$(bashio::services mqtt "password")
export MQTT_PORT=$(bashio::services mqtt "port")
```
that if the `bashio::services` works right, it should pull the host/port/un/pw, but without it showing up in debug logs, i can't verify that it's working... plus, like you said, it does show 'invalid host' which means it's not getting there...  I'm not seeing any negative lines in the mosquitto line on the broker indicating a failed connection (or even the first line of "new connection from").

I had already restarted HA this morning, but went ahead and just did it, with no change.  I'd wonder if it's a routing issue, with potentially the container not routing to non-containers, but that would not make sense since others would then be having issues with the Xcel meter not being reachable.

For what it's worth, I tried adding `host` `port` `username` and `password` that the python referenced into the config yaml under the Xcel iTron MQTT GUI/configuration tab, but no change there... still the 'invalid host' error.

on [The link](https://github.com/wingrunr21/hassio-xcel-itron-mqtt/blob/main/xcel-itron-mqtt/rootfs/etc/s6-overlay/s6-rc.d/xcel-itron-mqtt/run#L11-L12) you sent above, is there any way to have it use the "bashio::log.info" to output the MQTT Server/Port/User (not Password) ENV variables after bashio::services has attempted to fetch them, to make sure they're even being fetched correctly?   Say, after line 16?

**Comment by wingrunr21** [comment]
Sure, just pushed a commit to the `next` branch with the logging. Can you install off of that branch?

**Comment by wingrunr21** [comment]
ok, this is a low-risk change so I'll just push a patch version then

**Comment by wingrunr21** [comment]
Ya, seems like it. It's gotta be this: `ERROR: Got unexpected response from the API: Service not enabled`. I wonder if the Supervisor only enables the MQTT service when the Mosquitto addon is installed.

I have a random idea: can you install the Mosquitto addon and _not_ start it or otherwise change your MQTT config and see if things work?

**Comment by d2inco** [comment]
I *really* don't want to do that; I don't have a dev-system to try stuff out on, and i have too many things that talk to/through MQTT and don't want to risk them saying "oh, now I have a broker install locally, let me shift to that"...

Lemme ask this - are the bash lines `export MQTT_SERVER=$(bashio::services mqtt "host")` pulling from the installed service broker, or are they asking the *integration* what the config values are, isntead?

Just saw your edit (good!  really didn't want to do that!) -- is there a way to query the Intergration config-setting vs the mqtt broker Service setting?

**Comment by wingrunr21** [comment]
Ya, I can have the config lookup fall back to the services call if the UI config isn't set. I just need to add that to the UI and test it.

**Comment by robmaurizio** [comment]
any update on this?
Seems to work fine with the HA Mosquitto add-on but I cannot seem to get this Xcel iTron add-on to locate an external broker address. Tried to dig through but wasn't able to find the files from the logs.

**Comment by wingrunr21** [comment]
Yep: update is it hasn't been implemented

**Comment by robmaurizio** [comment]
Understood - thanks for the response :)

**Comment by wingrunr21** [comment]
Hi everyone,

I just pushed two updates to `main`:

1. There is now an `edge` version of the addon where I can test things. This should be considered an unstable version
2. The `edge` addon has the ability to manually configure the MQTT server. Those settings will override service discovery if you have the mosquito broker enabled as well. If folks want to give that a test and let me know if it's working for them, I'd appreciate it!

**Comment by robmaurizio** [comment]
Thanks. I've moved over to the edge add-on. Thanks!

**Comment by wingrunr21** [comment]
Is it working? I'd like to move this into the stable version but need testers

**Comment by jjcarrol** [comment]
@wingrunr21 I just installed the -edge addon. The external MQTT server seems to be working. One issue I noticed is that the topic_prefix value does not appear to be honored. It's currently just dumping data into the homeassistant/sensor topic.

Here's my MQTT config:

`server: mqtt.home.lan
port: 1883
user: mqtt
password: mqtt
topic_prefix: xcel`

**Comment by wingrunr21** [comment]
@jjcarrol can you update edge again and retry? looks like `bashio` shouldn't be wrapped in square brackets (so the variable export never happened)

**Comment by jjcarrol** [comment]
@wingrunr21 So I deleted and re-added your repo then reinstalled the -edge addon. I'm not sure if that was enough to force your updated version since the version number is the same? 

Anyway, my observed behavior is the same - the Xcel meter data is still being sent to the homeassistant/sensor topic.

Here's a message from 5 mins ago:

```
{
"device_class": "power", 
"unit_of_measurement": "W", 
"state_topic": "homeassistant/sensor/Instantaneous_Demand/value/state", 
"name": "Instantaneous Demand value", 
"unique_id": "xcel_itron_5_instantaneous_demand_value", 
"device": {"identifiers": ["XXXXXXXX"], 
"name": "Xcel Itron 5", 
"model": "1233", 
"sw_version": "10.5.803.1"}
}
```

**Comment by jrmclaugh** [comment]
@wingrunr21 I just installed -edge because I need the same feature.  I believe I have it fully configured, but I keep getting an error that seems to think the mqtt port number is empty

my config:
server: mqtt.***********
port: 1883
user: *****
password: ************
topic_prefix: xcel

I did start it up the first time with just the server: item set, so maybe it got in a bad state?

The errors:
`jq: error: syntax error, unexpected == (Unix shell quoting issues?) at <top-level>, line 1:
if (.mqtt.port, == null) then                
jq: error: syntax error, unexpected '|' (Unix shell quoting issues?) at <top-level>, line 3:
        elif (.mqtt.port, | type == "string") then                          
jq: error: syntax error, unexpected // (Unix shell quoting issues?) at <top-level>, line 4:
            .mqtt.port, // empty                        
jq: error: Possibly unterminated 'if' statement at <top-level>, line 1:
if (.mqtt.port, == null) then
jq: 4 compile errors`

and the line with "MQTT server config" is indeed missing a port number after the colon.

**Comment by jjcarrol** [comment]
@jrmclaugh FYI, I get that error too but I get a connection to my MQTT server:

```
[16:55:59] INFO: Initializing Xcel iTron2MQTT
s6-rc: info: service init-xcel-itron-mqtt successfully started
s6-rc: info: service xcel-itron-mqtt: starting
s6-rc: info: service xcel-itron-mqtt successfully started
s6-rc: info: service legacy-services: starting
[16:55:59] INFO: Starting Xcel iTron2MQTT
s6-rc: info: service legacy-services successfully started
jq: error: syntax error, unexpected == (Unix shell quoting issues?) at <top-level>, line 1:
if (.mqtt.port, == null) then                
jq: error: syntax error, unexpected '|' (Unix shell quoting issues?) at <top-level>, line 3:
        elif (.mqtt.port, | type == "string") then                          
jq: error: syntax error, unexpected // (Unix shell quoting issues?) at <top-level>, line 4:
            .mqtt.port, // empty                        
jq: error: Possibly unterminated 'if' statement at <top-level>, line 1:
if (.mqtt.port, == null) then
jq: 4 compile errors
[16:56:00] INFO: Meter config: 192.168.xx.xxx:8081
[16:56:00] INFO: MQTT server config: mqtt.xxxx.xxx:
INFO: Connected to MQTT Broker!
```

**Comment by wingrunr21** [comment]
@jjcarrol @jrmclaugh can you both tell me if you get the error on the latest commit to edge?

**Comment by jrmclaugh** [comment]
After a Rebuild, the port error appears to have been resolved.  Similar to an earlier comment: the version number stays the same, but it appears to have been updated all the same.

Also, these changes in edge did work to get my external MQTT broker working with this add on.  I originally just hadn't waited long enough for data to be populated and thought the port error was the cause (thanks for the tip @jjcarrol ).

**Comment by ZWood15** [comment]
I just found this discussion and was able to get my meter integrated with the edge version and an external MQTT broker. Thank you so much for the work on this add-on!!
