### ISSUE TITLE
SSLV3_ALERT_BAD_CERTIFICATE

### ISSUE THREAD

**Issue by kkellner** [wingrunr21/hassio-xcel-itron-mqtt#6]
New install. I have everything configured on the xcel side.  I configured the IP in the add-on, its the only field I updated from the default values.  When I start the add-on, I get the following error (below).  I tried to find `/configs/certs` folder via Studio Code Server, but I can't find it.  I assume it would have been auto-created.  I then tried to create `certs` folder and restart the add-on but still nothing.  I'm not sure the below error is related to my inability to locate the auto-generated certs, but that is what I'm currently thinking.  Seems similar to issue #3.

```
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-xcel-itron-mqtt: starting
[17:40:02] INFO: Initializing Xcel iTron2MQTT
s6-rc: info: service init-xcel-itron-mqtt successfully started
s6-rc: info: service xcel-itron-mqtt: starting
s6-rc: info: service xcel-itron-mqtt successfully started
s6-rc: info: service legacy-services: starting
[17:40:02] INFO: Starting Xcel iTron2MQTT
s6-rc: info: service legacy-services successfully started
Connected to MQTT Broker!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1046, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 1321, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.20.0.14', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/xcel_itron2mqtt/main.py", line 79, in <module>
    meter = xcelMeter(INTEGRATION_NAME, ip_address, port_num, creds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 67, in __init__
    details_dict = self.get_hardware_details(hw_info_url, hw_info_names)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 97, in get_hardware_details
    x = self.requests_session.get(query_url, verify=False, timeout=4.0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='172.20.0.14', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1000)')))
[17:40:03] INFO: Service Xcel iTron2MQTe exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service xcel-itron-mqtt: stopping
s6-rc: info: service xcel-itron-mqtt successfully stopped
s6-rc: info: service init-xcel-itron-mqtt: stopping
s6-rc: info: service init-xcel-itron-mqtt successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by kkellner** [comment]
More info on issue.  If I delete the add-on and re-add, I get a timeout on first startup, then a `SSLV3_ALERT_BAD_CERTIFICATE` every time after.  So I'm assuming it generates a bad cert file on the first run because of the timeout.  I can repeat the behavior every time I re-install the add-on.

As for the timeout error.  I know its the correct IP as I can see it in both DHCP server as well as Ubuntu admin console.  If I test via `nc`, I can see its listening:

```
$ nc -zv 172.20.0.14 8081
Connection to 172.20.0.14 port 8081 [tcp/sunproxyadmin] succeeded!
```

Addon startup error:
```
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='172.20.0.14', port=8081): Max retries exceeded with url: /sdev/sdi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3904891af0>, 'Connection to 172.20.0.14 timed out. (connect timeout=4.0)'))
[18:42:49] INFO: Service Xcel iTron2MQTe exited with code 1 (by signal 0)
```

**Comment by kkellner** [comment]
So sorry, I figured it out. I missed an important step on the configuration.  This was the step I missed:
```
Take the generated LDFI over to the [Meters and Devices](https://my.xcelenergy.com/MyAccount/s/meters-and-devices/manage-meters-and-devices) and add a new device. Fill out the form with your LDFI and wait for Xcel to send you an email that a new device was successfully added.
```
After I did this, it worked.   I still can't find the certs in the `configs` folder, but its working so its not critical.

Closing issue.

**Comment by wingrunr21** [comment]
If you are using the VSCode add-on you won't see it. The certs are stored in `addon_configs` which is at the same directory level as your `config` directory. The VSCode add-on loads `config` as its project root. You'll need to either SSH in or use desktop VSCode with an SSH remote.

**Comment by kkellner** [comment]
Oh!   Yep, I see them now.  Thank you so much for the clarification on location.
